cdk-deploy:
  # Use Node 16 on Alpine
  image: node:16-alpine
  stage: deploy
  script:
    - npm install --progress=false
    - npm run build
    - npm run cdk bootstrap
    - npm run cdk deploy
  needs:
    - project: $UI_UPSTREAM_PROJECT
      job: $UI_UPSTREAM_JOB
      ref: $UI_UPSTREAM_REF
      artifacts: true
