cdk-deploy:
  # Use Node 16 on Alpine
  image: node:16-alpine
  stage: deploy
  script:
    - apk --no-cache add curl zip
    - 'curl --location --output ui-build.zip --header "PRIVATE-TOKEN: $ARTIFACT_TOKEN" "$ARTIFACT_DOWNLOAD_URL"'
    - unzip ui-build.zip
    - npm install --progress=false
    - npm run build
    - npm run cdk bootstrap
    - npm run cdk deploy --require-approval=never
